### ISSUE TITLE
Compatibility with Ext:caretaker 1.0.3?

### ISSUE THREAD

**Issue by tobiasschaeferptb** [in2code-de/caretaker_instance#3]
Hello,

I installed the v12 version (https://github.com/in2code-de/caretaker_instance/tree/feature/V12) on a 12.4 system.
The caretaker server still runs under TYPO3 8.7 with the TER version 1.0.3. Should this work? On the caretaker server the check fails with "Command execution failed: Cant decode remote command result". Or is it necessary to use the v12 version (https://github.com/in2code-de/caretaker/tree/feature/V12) on the caretaker server?

Best regards,
Tobias Schaefer

**Comment by sbusemann** [comment]
We needed to update the encryption. Please note, that you should only use installations with HTTPS enabled from now on, as the addional encryption is removed. 
To get it work, you need to  update the caretaker client at the server and all clients.

**Comment by pixeldesu** [comment]
To be a bit more elaborate here, you need to update `caretaker_instance` on your Caretaker server to version [`2.3.0`](https://github.com/in2code-de/caretaker_instance/tree/2.3.0).

We changed the default transport encryption from RC4 back to the Base64 implementation because RC4 is incredibly outdated and was removed from OpenSSL 3.0. With newer PHP versions and newer servers shipping only with that, we noticed the client breaking.

Base64 is obviously not encryption, but Caretaker stems from a time where HTTPS was not standard yet and transport encryption was handled this way. Now, with HTTPS being basically anywhere, the extra encryption step is not really needed anymore.

We released `caretaker_instance` versions for all TYPO3 ranges from 8 to 12 to accommodate for this change (released = tagged them in our fork repository here)

**Comment by tobiasschaeferptb** [comment]
Hello,

Thanks for the quick answer. I installed version 2.1.3 on the caretaker server, but the check for the TYPO3 version and extension update still fails with "Command execution failed: Cannot decode command result". Is the TER version 1.0.3 of Ext:caretaker the right one to use on a 8.7 TYPO3 caretaker server or should it be a different one?
How do I generate the public and private key on a new client? In the past there was a update script that generated the keys.

Best regards,
Tobias Schaefer

**Comment by pixeldesu** [comment]
As this is a fork we don't have any relation to the TER releases.

In order to be compatible with `feature/V12` (or just 5.0.0) you need `caretaker_instance` 2.3.0 on your server-side.

And with the base64 transport the client private/public key technically becomes irrelevant, I think it is required still but I haven't found a clean solution for this yet. I generally focused on getting our current monitored sites to work again at first.

**Comment by tobiasschaeferptb** [comment]
Hello,

Sorry for the confusion. I meant to write "I installed version 2.3.0 on the caretaker server", not "I installed version 2.1.3 on the caretaker server". I also installed the current master and develop version of caretaker (https://github.com/in2code-de/caretaker/tree/master, https://github.com/in2code-de/caretaker/tree/develop), but then I couldn't edit the settings for an existing instance. Clicking on the edit button in the list module or in the caretaker module didn't do anything. There were no requests in the apache logs when I clicked on the edit button. At the end with the fork version 1.0.3 (develop or master) of caretaker and the fork version 2.3.0 of caretaker_instance the checks failed with "Command execution failed: Cannot decode command result".

Best regards,
Tobias Schaefer
